package com.example.contentanalyzer.data.api.models

import com.google.gson.annotations.SerializedName

/**
 * Prediction result from classification models
 */
data class HuggingFacePrediction(
    @SerializedName("label")
    val label: String,
    @SerializedName("score")
    val score: Float
)

/**
 * Request for Zero-Shot Classification
 */
data class ZeroShotRequest(
    @SerializedName("inputs")
    val inputs: String,
    @SerializedName("parameters")
    val parameters: ZeroShotParameters = ZeroShotParameters()
)

data class ZeroShotParameters(
    @SerializedName("candidate_labels")
    val candidateLabels: List<String> = listOf(
        "This text was generated by AI",
        "This text was written by a human"
    ),
    @SerializedName("multi_label")
    val multiLabel: Boolean = false
)

/**
 * Response from Zero-Shot Classification
 */
data class ZeroShotResponse(
    @SerializedName("sequence")
    val sequence: String,
    @SerializedName("labels")
    val labels: List<String>,
    @SerializedName("scores")
    val scores: List<Float>
)

/**
 * Error response model
 */
data class HuggingFaceError(
    @SerializedName("error")
    val error: String? = null,
    @SerializedName("estimated_time")
    val estimatedTime: Float? = null,
    @SerializedName("warnings")
    val warnings: List<String>? = null
)

/**
 * Wrapper for API responses to handle different types and errors
 */
sealed class ApiResponse {
    data class Success(val predictions: List<HuggingFacePrediction>) : ApiResponse()
    data class ZeroShotSuccess(val responses: List<ZeroShotResponse>) : ApiResponse()
    data class Error(val error: HuggingFaceError) : ApiResponse()
    object Empty : ApiResponse()
}

/**
 * Internal representation of parsed analysis result
 */
data class ParsedAnalysisResult(
    val aiProbability: Float,
    val humanProbability: Float,
    val rawPredictions: Map<String, Float>,
    val modelConfidence: Float,
    val responseType: String,
    val isValid: Boolean
)
